services:
  web-server:
    image: nginx:mainline-alpine
    ports:
      - 8080:80
    volumes:
      - ./site/index.html:/usr/share/nginx/html/index.html:ro
      - ./site/dist:/usr/share/nginx/html/dist:ro
