---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Build & pack"
        run: |
          yarn install --dev
          yarn run build release

      - name: "Create release"
        uses: fnkr/github-action-ghr@v1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GHR_PATH: wcd.tar.gz
